version: "3.8"

services:

  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8001:8000
    depends_on:
      sql_db_pg:
        condition: service_started

  # Node Server
  node:
    build:
      context: .
      target: node
    volumes:
      - ./:/var/www
      # - ./node_modules:/var/www/node_modules
    ports:
      - 5173:5173
    tty: true
    command: sh -c "npm run dev -- --host=0.0.0.0"

  adminer:
    image: adminer
    environment:
      TZ: America/Hermosillo
    ports:
      - 8081:8080
    depends_on:
      sql_db_pg:
        condition: service_started

  # Database Server
  sql_db_pg:
    image: postgres:15.2
    container_name: sql_db_pg
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: utn_osil
      TZ: America/Hermosillo
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5431:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5