version: "3.8"

services:

  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      sql_db:
        condition: service_started

  adminer:
    image: adminer
    environment:
      TZ: America/Hermosillo
    ports:
      - 8080:8080
    depends_on:
      sql_db:
        condition: service_started

  # Database Server
  sql_db:
    image: postgres:15.2
    container_name: sql_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: utn_osil
      TZ: America/Hermosillo
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5